import threading
import time
import pyautogui

from mousemover.models import AppConfig, MovementContext
from .monitors import monitors, point_on_any_monitor
from .plugin_loader import load_plugins


class Engine:
    def __init__(self, config: AppConfig, hooks, logger):
        self.config = config
        self.hooks = hooks
        self.logger = logger
        self.plugins = load_plugins()
        self.plugin = None
        self.monitor = None
        self.running = False
        self._worker = None
        self.last_error = None
        self._configure()

    def _configure(self):
        mons = monitors()
        if not mons:
            raise RuntimeError("Nenhum monitor detectado.")

        if self.config.monitor < 0 or self.config.monitor >= len(mons):
            raise ValueError(f"Monitor {self.config.monitor} inválido.")

        self.monitor = mons[self.config.monitor]

        if self.config.plugin not in self.plugins:
            names = ", ".join(self.plugins)
            raise ValueError(
                f"Plugin '{self.config.plugin}' não encontrado. Disponíveis: {names}"
            )

        self.plugin = self.plugins[self.config.plugin]

        if self.config.jitter_min < 0:
            raise ValueError("jitter_min não pode ser negativo.")
        if self.config.jitter_max < self.config.jitter_min:
            raise ValueError("jitter_max deve ser >= jitter_min.")
        if self.config.interval <= 0:
            raise ValueError("interval deve ser > 0.")
        if self.config.watchdog <= 0:
            raise ValueError("watchdog deve ser > 0.")

    def reload_plugins(self):
        current_name = self.config.plugin
        self.plugins = load_plugins()
        if current_name in self.plugins:
            self.plugin = self.plugins[current_name]
        self.logger.info("Plugins recarregados: %s", ", ".join(self.plugins))
        return self.plugins

    def select_plugin(self, name: str):
        self.plugins = load_plugins()
        if name not in self.plugins:
            raise ValueError(f"Plugin '{name}' não encontrado.")
        self.config.plugin = name
        self.plugin = self.plugins[name]
        self.logger.info("Plugin selecionado: %s", name)

    def select_monitor(self, index: int):
        mons = monitors()
        if index < 0 or index >= len(mons):
            raise ValueError(f"Monitor {index} inválido.")
        self.config.monitor = index
        self.monitor = mons[index]
        self.logger.info("Monitor selecionado: %d", index)

    def _context(self):
        pos = pyautogui.position()
        return MovementContext(
            monitor=self.monitor,
            interval=self.config.interval,
            jitter_min=self.config.jitter_min,
            jitter_max=self.config.jitter_max,
            last_user_activity=self.hooks.last_user_activity,
            now=time.monotonic(),
            current_x=pos.x,
            current_y=pos.y,
        )

    def _interrupt_reason(self):
        if self.hooks.kill_event.is_set():
            return "kill"
        if self.hooks.pause_event.is_set():
            return "pause"
        if self.config.mouse_hook and self.hooks.user_mouse_event.is_set():
            return "mouse"
        return None

    def _interruptible_wait(self, seconds):
        end = time.monotonic() + seconds
        while time.monotonic() < end:
            reason = self._interrupt_reason()
            if reason:
                return reason
            time.sleep(min(0.1, max(0, end - time.monotonic())))
        return None

    def _move_and_watch(self, x: int, y: int):
        if not point_on_any_monitor(x, y):
            self.logger.error(
                "Plugin tentou mover para coordenada fora dos monitores: (%d,%d).", x, y
            )
            return False

        before = pyautogui.position()

        # Ignore mouse-hook callbacks generated by our own movement.
        self.hooks.mark_internal_movement(max(0.75, self.config.watchdog))
        pyautogui.moveTo(x, y, duration=min(0.4, self.config.watchdog / 2))

        deadline = time.monotonic() + self.config.watchdog
        while time.monotonic() < deadline:
            current = pyautogui.position()
            if current.x == x and current.y == y:
                self.logger.info(
                    "Mouse: (%d,%d) -> (%d,%d) | monitor=%d | plugin=%s",
                    before.x, before.y, x, y,
                    self.config.monitor, self.config.plugin,
                )
                return True

            if self._interrupt_reason():
                return False

            time.sleep(0.05)

        current = pyautogui.position()
        self.logger.error(
            "WATCHDOG: destino (%d,%d) não atingido em %.2fs; posição atual=(%d,%d).",
            x, y, self.config.watchdog, current.x, current.y,
        )
        return False

    def run(self):
        self.running = True
        self.last_error = None
        self.hooks.pause_event.clear()
        self.hooks.resume_event.clear()
        self.hooks.clear_user_mouse_event()

        self.logger.info(
            "Loop iniciado | monitor=%d | plugin=%s | intervalo=%.2fs",
            self.config.monitor, self.config.plugin, self.config.interval,
        )

        try:
            cycles = 0
            while not self.hooks.kill_event.is_set():
                reason = self._interrupt_reason()
                if reason:
                    if reason == "mouse":
                        self.logger.warning("Loop interrompido por movimento do usuário.")
                    elif reason == "pause":
                        self.logger.info("Loop pausado.")
                    return reason

                ctx = self._context()
                points = self.plugin.get_next_points(ctx)

                for x, y in points:
                    reason = self._interrupt_reason()
                    if reason:
                        return reason

                    if not self._move_and_watch(int(x), int(y)):
                        reason = self._interrupt_reason()
                        if reason:
                            return reason
                        self.last_error = "watchdog"
                        return "watchdog"

                    reason = self._interruptible_wait(self.config.interval)
                    if reason:
                        return reason

                # Empty point list is valid, e.g. human-idle plugin.
                if not points:
                    reason = self._interruptible_wait(min(self.config.interval, 1.0))
                    if reason:
                        return reason

                cycles += 1
                if self.config.once and cycles >= 1:
                    self.logger.info("--once concluído.")
                    return "once"

            return "kill"
        except Exception as exc:
            self.last_error = str(exc)
            self.logger.exception("Erro no engine: %s", exc)
            return "error"
        finally:
            self.running = False

    def start_background(self, callback=None):
        if self.running:
            return

        def target():
            reason = self.run()
            if callback:
                callback(reason)

        self._worker = threading.Thread(target=target, daemon=True)
        self._worker.start()

    def request_stop(self):
        self.hooks.pause_event.set()

    def resume_background(self, callback=None):
        self.hooks.pause_event.clear()
        self.hooks.resume_event.clear()
        self.hooks.clear_user_mouse_event()
        self.start_background(callback)
